# Generated by Django 6.0 on 2025-12-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
